export const defaultTemplate = {
  width: 1240,
  height: 1754,
  fonts: [
    {
      fontFamily: "Inter",
    },
  ],
  pages: [
    {
      id: "page1",
      children: [
        {
          id: "background",
          type: "figure",
          name: "Page Background",
          x: 0,
          y: 0,
          width: 1240,
          height: 1754,
          fill: "#FFFFFF",
          selectable: false,
          alwaysOnBottom: true,
        },
        // Document Top Header Banner
        {
          id: "header-bg",
          type: "figure",
          name: "Header Background",
          x: 0,
          y: 0,
          width: 1240,
          height: 190,
          fill: "#0F172A",
        },
        {
          id: "doc-title",
          type: "text",
          name: "Document Title",
          x: 220,
          y: 50,
          width: 800,
          height: 48,
          text: "MOTOR VEHICLE BILL OF SALE",
          fontSize: 36,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#FFFFFF",
          align: "center",
        },
        {
          id: "doc-subtitle",
          type: "text",
          name: "Document Subtitle",
          x: 270,
          y: 108,
          width: 700,
          height: 32,
          text: "Official Legal Transfer of Ownership Document",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#94A3B8",
          align: "center",
        },

        // Section 1: Seller Information
        {
          id: "sec1-bg",
          type: "figure",
          name: "Seller Section Box",
          x: 64,
          y: 230,
          width: 1112,
          height: 270,
          fill: "#F8FAFC",
          stroke: "#CBD5E1",
          strokeWidth: 1,
          cornerRadius: 12,
        },
        {
          id: "sec1-title",
          type: "text",
          name: "Seller Section Title",
          x: 96,
          y: 255,
          width: 400,
          height: 28,
          text: "1. SELLER INFORMATION",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "seller-name-label",
          type: "text",
          name: "Seller Name Label",
          x: 96,
          y: 295,
          width: 250,
          height: 24,
          text: "Full Name:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "seller-name",
          type: "text",
          name: "Seller Full Name",
          x: 96,
          y: 322,
          width: 1048,
          height: 32,
          text: "Johnathan Vance",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1D4ED8",
          align: "left",
        },
        {
          id: "seller-address-label",
          type: "text",
          name: "Seller Address Label",
          x: 96,
          y: 370,
          width: 250,
          height: 24,
          text: "Street Address & City:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "seller-address",
          type: "text",
          name: "Seller Address Value",
          x: 96,
          y: 397,
          width: 1048,
          height: 32,
          text: "742 Evergreen Terrace, Springfield, IL 62704",
          fontSize: 19,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#1E293B",
          align: "left",
        },

        // Section 2: Buyer Information
        {
          id: "sec2-bg",
          type: "figure",
          name: "Buyer Section Box",
          x: 64,
          y: 535,
          width: 1112,
          height: 270,
          fill: "#F8FAFC",
          stroke: "#CBD5E1",
          strokeWidth: 1,
          cornerRadius: 12,
        },
        {
          id: "sec2-title",
          type: "text",
          name: "Buyer Section Title",
          x: 96,
          y: 560,
          width: 400,
          height: 28,
          text: "2. BUYER INFORMATION",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "buyer-name-label",
          type: "text",
          name: "Buyer Name Label",
          x: 96,
          y: 600,
          width: 250,
          height: 24,
          text: "Full Name:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "buyer-name",
          type: "text",
          name: "Buyer Full Name",
          x: 96,
          y: 627,
          width: 1048,
          height: 32,
          text: "Eleanor Rigby",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1D4ED8",
          align: "left",
        },
        {
          id: "buyer-address-label",
          type: "text",
          name: "Buyer Address Label",
          x: 96,
          y: 675,
          width: 250,
          height: 24,
          text: "Street Address & City:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "buyer-address",
          type: "text",
          name: "Buyer Address Value",
          x: 96,
          y: 702,
          width: 1048,
          height: 32,
          text: "104 Abbey Road, Seattle, WA 98101",
          fontSize: 19,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#1E293B",
          align: "left",
        },

        // Section 3: Vehicle Information
        {
          id: "sec3-bg",
          type: "figure",
          name: "Vehicle Section Box",
          x: 64,
          y: 840,
          width: 1112,
          height: 370,
          fill: "#F8FAFC",
          stroke: "#CBD5E1",
          strokeWidth: 1,
          cornerRadius: 12,
        },
        {
          id: "sec3-title",
          type: "text",
          name: "Vehicle Section Title",
          x: 96,
          y: 865,
          width: 400,
          height: 28,
          text: "3. VEHICLE DESCRIPTION & VIN",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "vehicle-make-label",
          type: "text",
          name: "Vehicle Make Label",
          x: 96,
          y: 905,
          width: 250,
          height: 24,
          text: "Year, Make & Model:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "vehicle-details",
          type: "text",
          name: "Vehicle Details Value",
          x: 96,
          y: 932,
          width: 1048,
          height: 32,
          text: "2024 Tesla Model Y Long Range (SUV, Solid Black)",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "vin-label",
          type: "text",
          name: "VIN Label",
          x: 96,
          y: 980,
          width: 300,
          height: 24,
          text: "Vehicle Identification Number (VIN):",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "vin-number",
          type: "text",
          name: "VIN Number Value",
          x: 96,
          y: 1007,
          width: 1048,
          height: 32,
          text: "5YJ3E1EA1KF123456",
          fontSize: 20,
          fontFamily: "Courier New, monospace",
          fontWeight: "bold",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "odometer-label",
          type: "text",
          name: "Odometer Label",
          x: 96,
          y: 1055,
          width: 250,
          height: 24,
          text: "Odometer Reading (Miles):",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "odometer-reading",
          type: "text",
          name: "Odometer Reading Value",
          x: 96,
          y: 1082,
          width: 1048,
          height: 32,
          text: "12,450 Miles (Actual Mileage Certified)",
          fontSize: 19,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#1E293B",
          align: "left",
        },

        // Section 4: Purchase Price & Terms
        {
          id: "sec4-bg",
          type: "figure",
          name: "Payment Section Box",
          x: 64,
          y: 1245,
          width: 1112,
          height: 240,
          fill: "#F8FAFC",
          stroke: "#CBD5E1",
          strokeWidth: 1,
          cornerRadius: 12,
        },
        {
          id: "sec4-title",
          type: "text",
          name: "Payment Section Title",
          x: 96,
          y: 1270,
          width: 400,
          height: 28,
          text: "4. PURCHASE PRICE & WARRANTY",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#0F172A",
          align: "left",
        },
        {
          id: "price-label",
          type: "text",
          name: "Purchase Price Label",
          x: 96,
          y: 1310,
          width: 250,
          height: 24,
          text: "Agreed Purchase Price:",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#475569",
          align: "left",
        },
        {
          id: "purchase-price",
          type: "text",
          name: "Purchase Price Value",
          x: 96,
          y: 1337,
          width: 1048,
          height: 36,
          text: "$28,500.00 USD (Twenty-Eight Thousand Five Hundred Dollars)",
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#15803D",
          align: "left",
        },
        {
          id: "warranty-terms",
          type: "text",
          name: "Warranty Statement",
          x: 96,
          y: 1390,
          width: 1048,
          height: 40,
          text: "Condition: Sold AS-IS with no express or implied warranties. Seller guarantees free and clear title.",
          fontSize: 15,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#64748B",
          align: "left",
        },

        // Signatures Line
        {
          id: "sig-seller-label",
          type: "text",
          name: "Seller Signature Line",
          x: 96,
          y: 1560,
          width: 450,
          height: 30,
          text: "Seller Signature: _______________________ Date: ________",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#334155",
          align: "left",
        },
        {
          id: "sig-buyer-label",
          type: "text",
          name: "Buyer Signature Line",
          x: 650,
          y: 1560,
          width: 450,
          height: 30,
          text: "Buyer Signature: _______________________ Date: ________",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#334155",
          align: "left",
        },
      ],
      background: "#FFFFFF",
    },
  ],
};
