export const defaultTemplate = {
  width: 1240,
  height: 1754,
  fonts: [
    {
      fontFamily: "Inter",
    },
  ],
  pages: [
    {
      id: "page1",
      children: [
        {
          id: "background",
          type: "figure",
          name: "Page Background",
          x: 0,
          y: 0,
          width: 1240,
          height: 1754,
          fill: "#FFFFFF",
          selectable: false,
          alwaysOnBottom: true,
        },
        {
          id: "header-gradient",
          type: "figure",
          name: "Header Background",
          x: 0,
          y: 0,
          width: 1240,
          height: 205,
          fill: "linear-gradient(90deg, #1E40AF 0%, #3B82F6 100%)",
        },
        {
          id: "title",
          type: "text",
          name: "Bill of Sale Title",
          x: 340,
          y: 58,
          width: 560,
          height: 50,
          text: "BILL OF SALE / ДОГОВІР КУПІВЛІ-ПРОДАЖУ",
          fontSize: 34,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#FFFFFF",
          align: "center",
        },
        {
          id: "subtitle",
          type: "text",
          name: "Subtitle",
          x: 380,
          y: 115,
          width: 480,
          height: 39,
          text: "Vehicle & Property Transfer Agreement",
          fontSize: 22,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#DBEAFE",
          align: "center",
        },

        // Section 1: Parties Information
        {
          id: "parties-bg",
          type: "figure",
          name: "Parties Background",
          x: 64,
          y: 250,
          width: 1112,
          height: 580,
          fill: "#F8FAFC",
          stroke: "#E2E8F0",
          strokeWidth: 1,
          cornerRadius: 14,
        },
        {
          id: "seller-label",
          type: "text",
          name: "Seller Label",
          x: 96,
          y: 285,
          width: 300,
          height: 28,
          text: "Seller Information (Продавець)",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1E293B",
          align: "left",
        },
        {
          id: "seller-name",
          type: "text",
          name: "Seller Name Value",
          x: 96,
          y: 320,
          width: 1048,
          height: 40,
          text: "Олександр Коваленко (Паспорт: КМ123456, ІПН: 3284910293)",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#2563EB",
          align: "left",
        },
        {
          id: "buyer-label",
          type: "text",
          name: "Buyer Label",
          x: 96,
          y: 410,
          width: 300,
          height: 28,
          text: "Buyer Information (Покупець)",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1E293B",
          align: "left",
        },
        {
          id: "buyer-name",
          type: "text",
          name: "Buyer Name Value",
          x: 96,
          y: 445,
          width: 1048,
          height: 40,
          text: "Марія Петренко (Паспорт: АА987654, ІПН: 2984019284)",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#2563EB",
          align: "left",
        },

        {
          id: "date-location-label",
          type: "text",
          name: "Date Location Label",
          x: 96,
          y: 535,
          width: 350,
          height: 28,
          text: "Date & Location (Дата та Місто)",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1E293B",
          align: "left",
        },
        {
          id: "date-location-val",
          type: "text",
          name: "Date Location Value",
          x: 96,
          y: 570,
          width: 1048,
          height: 40,
          text: "10 вересня 2026 р., м. Київ, Україна",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#0F172A",
          align: "left",
        },

        // Section 2: Vehicle / Item Details
        {
          id: "item-bg",
          type: "figure",
          name: "Item Details Background",
          x: 64,
          y: 870,
          width: 1112,
          height: 520,
          fill: "#F8FAFC",
          stroke: "#E2E8F0",
          strokeWidth: 1,
          cornerRadius: 14,
        },
        {
          id: "item-title",
          type: "text",
          name: "Item Description Label",
          x: 96,
          y: 905,
          width: 450,
          height: 28,
          text: "Vehicle / Property Description (Об'єкт угоди)",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1E293B",
          align: "left",
        },
        {
          id: "item-details",
          type: "text",
          name: "Item Details Value",
          x: 96,
          y: 945,
          width: 1048,
          height: 70,
          text: "Легковий автомобіль 2024 Tesla Model Y (Колір: Black, VIN: 5YJ3E1EA1KF123456, Держ. номер: KA7777BP)",
          fontSize: 20,
          fontFamily: "Inter",
          fontWeight: "normal",
          fill: "#0F172A",
          align: "left",
          lineHeight: 1.4,
        },
        {
          id: "price-label",
          type: "text",
          name: "Purchase Price Label",
          x: 96,
          y: 1070,
          width: 350,
          height: 28,
          text: "Purchase Price / Сума угоди ($)",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#1E293B",
          align: "left",
        },
        {
          id: "price-val",
          type: "text",
          name: "Purchase Price Value",
          x: 96,
          y: 1105,
          width: 1048,
          height: 40,
          text: "$25,000.00 USD (Двадцять п'ять тисяч доларів США)",
          fontSize: 24,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#16A34A",
          align: "left",
        },

        // Signatures area
        {
          id: "sig-seller",
          type: "text",
          name: "Seller Signature Label",
          x: 96,
          y: 1450,
          width: 400,
          height: 30,
          text: "Підпис продавця: ___________________",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "500",
          fill: "#475569",
          align: "left",
        },
        {
          id: "sig-buyer",
          type: "text",
          name: "Buyer Signature Label",
          x: 700,
          y: 1450,
          width: 400,
          height: 30,
          text: "Підпис покупця: ___________________",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "500",
          fill: "#475569",
          align: "left",
        },
      ],
      background: "#FFFFFF",
    },
  ],
};
